In [1]:
%pip install selenium
%pip install webdriver-manager
%pip install beautifulsoup4

Requirement already satisfied: selenium in c:\users\alima\anaconda3\lib\site-packages (4.1.3)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\alima\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure,socks]~=1.26 in c:\users\alima\anaconda3\lib\site-packages (from selenium) (1.26.7)
Requirement already satisfied: trio~=0.17 in c:\users\alima\anaconda3\lib\site-packages (from selenium) (0.20.0)
Requirement already satisfied: cffi>=1.14 in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.6)
Requirement already satisfied: sortedcontainers in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: outcome in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: idna in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.2)
Requirement already satisfied: sniffio in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\alima\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.2.0)
Requirement already satisfied: pycparser in c:\users\alima\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\alima\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\alima\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\alima\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (21.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\alima\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (3.4.8)
Requirement already satisfied: certifi in c:\users\alima\anaconda3\lib\site-packages (from urllib3[secure,socks]~=1.26->selenium) (2021.10.8)
Requirement already satisfied: six>=1.5.2 in c:\users\alima\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure,socks]~=1.26->selenium) (1.16.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\alima\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: webdriver-manager in c:\users\alima\anaconda3\lib\site-packages (3.5.4)
Requirement already satisfied: requests in c:\users\alima\anaconda3\lib\site-packages (from webdriver-manager) (2.26.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\alima\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\alima\anaconda3\lib\site-packages (from requests->webdriver-manager) (2021.10.8)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\alima\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\alima\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.7)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: beautifulsoup4 in c:\users\alima\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\alima\anaconda3\lib\site-packages (from beautifulsoup4) (2.2.1)
Note: you may need to restart the kernel to use updated packages.

In [2]:
%pip install fake-useragent

Requirement already satisfied: fake-useragent in c:\users\alima\anaconda3\lib\site-packages (0.1.11)
Note: you may need to restart the kernel to use updated packages.

In [60]:
from fake_useragent import UserAgent
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait as wait
from selenium.webdriver.support import expected_conditions as EC

usuario=UserAgent().random

print(usuario)

Mozilla/5.0 (Windows; U; Windows NT 5.1; ru-RU) AppleWebKit/533.18.1 (KHTML, like Gecko) Version/5.0.2 Safari/533.18.5

In [4]:
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
PATH=ChromeDriverManager().install()
driver=webdriver.Chrome(PATH)

opciones=Options()

opciones.add_experimental_option('excludeSwitches', ['enable-automation'])
opciones.add_experimental_option('useAutomationExtension', False)
opciones.headless=False
opciones.add_argument('--start-maximized')
#opciones.add_argument('--incognito')
#opciones.add_extension('driver/adblock.crx')       # adblocker


#opciones.add_argument('user-data-dir=selenium') 
#opciones.add_argument('proxy-server=5.152.175.13.2:2580')

====== WebDriver manager ======
Current google-chrome version is 100.0.4896
Get LATEST chromedriver version for 100.0.4896 google-chrome
Driver [C:\Users\alima\.wdm\drivers\chromedriver\win32\100.0.4896.60\chromedriver.exe] found in cache
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/4228707673.py:5: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH)

In [84]:
import  csv
from selenium.common.exceptions import TimeoutException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium import webdriver
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options

import numpy as np
from random import randint
import requests as req
import pandas as pd
import time
from time import sleep
from bs4 import BeautifulSoup as bs

In [6]:
url='https://www.coches.net/'

In [72]:
PATH=ChromeDriverManager().install()

====== WebDriver manager ======
Current google-chrome version is 100.0.4896
Get LATEST chromedriver version for 100.0.4896 google-chrome
Trying to download new driver from https://chromedriver.storage.googleapis.com/100.0.4896.60/chromedriver_win32.zip
Driver has been saved in cache [C:\Users\alima\.wdm\drivers\chromedriver\win32\100.0.4896.60]

In [165]:
URL='https://www.milanuncios.com/coches-de-segunda-mano/?fromSearch=1&orden=relevance&pagina='
driver=webdriver.Chrome(PATH, options=opciones)
   

    
    

#driver.implicitly_wait(10)
#wait = WebDriverWait(driver, 10)
#for i in range(200):
    

driver.get((URL+str(1)))




time.sleep(2)
cookies=driver.find_element_by_xpath('//*[@id="app"]/div[2]/div[1]/div/div/div/footer/div/button[2]')
cookies.click()
#time.sleep(2)
#driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
#wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".ma-ButtonBasic--primary > span:nth-child(i)")))



main=driver.find_element(By.TAG_NAME,'main')
coche=main.find_elements_by_class_name('ma-AdCardV2-upperGroup')

data=[]
for e in coche:
    data.append(e.text.split('\n'))

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/666043186.py:2: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH, options=opciones)
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/666043186.py:19: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cookies=driver.find_element_by_xpath('//*[@id="app"]/div[2]/div[1]/div/div/div/footer/div/button[2]')

In [167]:
cars=pd.DataFrame(data)
cars

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,CITROEN - C3 AIRCROSS,Precio al contado,18.500 €,IVA Incluido,Precio financiado,15.600 €,Valladolid (Valladolid),2020,Manual,5 puertas,"¿estás buscando coche? en palausa, concesionar...",Leer más,#Citroen en Valladolid,Hace 390 días
1,AUDI - A4,10.000 €,León (León),192.000 kms,2011,Manual,"ITV , ok , REVISONES , AMORTIGUADORES , ETC A ...",#Audi en León,None,None,None,None,None,None

In [138]:
 # tres paginas


def linkedin(pages):

    

    data=[]
    pages=np.arange(1,54,1)

    for i in pages:

        page=(URL+str(i))

        html=req.get(page).content   # el html

        sopa=bs(html, 'html.parser')
        main=sopa.find('main')

        for oferta in main.find_all(class_='ma-AdCardV2-upperGroup'):

                # bucle para las ofertas
                modelo=oferta.find('h2').text.strip()   #modelo

                precio=oferta.find('span', class_="ma-AdPrice-value ma-AdPrice-value--dark ma-AdPrice-value--heading--s").text.strip()   # precio

                link=oferta.find('a', class_="ma-AdCardListingV2-TitleLink").attrs['href']  # link de la compañia

                #lugar=oferta.find('span', class_="job-search-card__location").text.strip()  # lugar

                #link_ofer=oferta.find('a', class_="base-card__full-link").attrs['href']   # link de la oferta

                #fecha=oferta.find('time').attrs['datetime']       # fecha de publicacion



                data.append({
                    'modelo': modelo,
                    'name': precio,
                    'link de la oferta': link,
                    #'location': lugar,
                    #'link de la oferta': link_ofer,
                    #'datetime': fecha
                })
                
        return pd.DataFrame(data)

In [139]:
linkedin(np.arange(1,4,1))

,modelo,name,link de la oferta
0,FORD - ECOSPORT 1.0 ECOBOOST 92KW 125CV TREND,14.500 €,/ford-de-segunda-mano/ford-ecosport-1-0-ecoboo...
1,VOLKSWAGEN - POLO ADVANCE 1.0 75CV BMT,11.500 €,/volkswagen-de-segunda-mano/volkswagen-polo-ad...

In [125]:
df=pd.DataFrame(lst)
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,PORSCHE - MACAN S DIESEL,Precio al contado,56.900 €,IVA Incluido,Precio financiado,53.900 €,Quart de Poblet (Valencia),85.015 kms,2018,Automático,Concesionario oficial porsche valencia y caste...,Leer más,#Porsche en Valencia,Hace 3 días
1,BMW - SERIE 3,3.750 €,Alcalá de Henares (Madrid),280.000 kms,2011,Manual,Se vende BMW 320d 2011 motor 2.0 163cv equipad...,Leer más,#BMW en Madrid,None,None,None,None,None
2,OFERTA PATROCINADA,TU SEGURO… EN 20 SEGUNDOS,Es todo lo que necesitas para tener el mejor p...,Leer más,None,None,None,None,None,None,None,None,None,None
3,VOLKSWAGEN - POLO ADVANCE 1.0 75CV BMT,Precio al contado,11.500 €,IVA Incluido,Precio financiado,11.500 €,Jerez de la Frontera (Cádiz),65.960 kms,2015,Manual,"No obligamos a financiar, nuestros precios son...",Leer más,#Volkswagen en Cádiz,None
4,AUDI - Q5 2.0 TDI CLEAN 110KW QUATTRO ADVANCED ED,Precio al contado,28.900 €,IVA Incluido,Precio financiado,28.900 €,Jerez de la Frontera (Cádiz),64.242 kms,2017,Manual,-EXTRAS-- - Sensores de aparcamiento delantero...,Leer más,#Audi en Cádiz,None

In [ ]:
#texto=driver.find_element_by_xpath('/html/body/main/div/input')
#texto.send_keys('the boys diabolico')
#texto.send_keys(u'\ue007')

In [168]:
driver.quit()

In [140]:
driver=webdriver.Chrome(PATH, options=opciones)
   

    
    
#pages = np.arange(1, 200, 1)
data=[]


    
page=URL+str(2)

driver.get(page)

sleep(randint(2,5))




#wait.until(EC.visibility_of_element_located((By.CSS_SELECTOR, (".ma-LayoutBasicFooter-paper > div:nth-child(1) > img:nth-child(3)").replace(' ','.'))))
#FUNCIONA SIN EL BUCLE, PILLAMOS SOLO DE UNA PAGINA


main=driver.find_element(By.TAG_NAME,'main')
coche=main.find_elements_by_class_name('ma-AdCardV2-upperGroup')

dato=[]
for e in coche:
    dato.append(e.text.split('\n'))

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/174656859.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH, options=opciones)
C:\Users\alima\anaconda3\lib\site-packages\selenium\webdriver\remote\webelement.py:464: UserWarning: find_elements_by_class_name is deprecated. Please use find_elements(by=By.CLASS_NAME, value=name) instead
  warnings.warn("find_elements_by_class_name is deprecated. Please use find_elements(by=By.CLASS_NAME, value=name) instead")

In [124]:
g=pd.DataFrame(dato)
g.head()
g.shape

(3, 15)

In [161]:
driver=webdriver.Chrome(PATH, options=opciones)

#for page in range(1,2):
url=URL+str(1)
driver.get(url)

WebDriverWait(driver, 10).until_not(EC.presence_of_element_located((By.XPATH, ('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article[31]/div/div'))))
dato=[]
for i in range(1,5):    
    coche=driver.find_element_by_xpath('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article['+str(i)+']/div/div')
    dato.append(coche.text.split('\n'))
dato

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/889245381.py:1: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH, options=opciones)
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/889245381.py:10: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  coche=driver.find_element_by_xpath('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article['+str(i)+']/div/div')

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article[3]/div/div"}
  (Session info: chrome=100.0.4896.88)
Stacktrace:
Backtrace:
	Ordinal0 [0x00417413+2389011]
	Ordinal0 [0x003A9F61+1941345]
	Ordinal0 [0x0029C658+837208]
	Ordinal0 [0x002C91DD+1020381]
	Ordinal0 [0x002C949B+1021083]
	Ordinal0 [0x002F6032+1204274]
	Ordinal0 [0x002E4194+1130900]
	Ordinal0 [0x002F4302+1196802]
	Ordinal0 [0x002E3F66+1130342]
	Ordinal0 [0x002BE546+976198]
	Ordinal0 [0x002BF456+980054]
	GetHandleVerifier [0x005C9632+1727522]
	GetHandleVerifier [0x0067BA4D+2457661]
	GetHandleVerifier [0x004AEB81+569713]
	GetHandleVerifier [0x004ADD76+566118]
	Ordinal0 [0x003B0B2B+1968939]
	Ordinal0 [0x003B5988+1989000]
	Ordinal0 [0x003B5A75+1989237]
	Ordinal0 [0x003BECB1+2026673]
	BaseThreadInitThunk [0x77A0FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77B57A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77B57A4E+238]

## COCHES.com

In [297]:
url3='https://www.coches.com/coches-segunda-mano/coches-ocasion.htm?page=4'

In [210]:
data=[]
html=req.get(url3).content 
sopa=bs(html, 'html.parser')

main=sopa.find(id='vo-results')
for oferta in sopa.find(id='vo-results'):
    modelo=main.find(class_='make-model-version').text
    precio=main.find(class_='price').text
    data.append({'precio':precio, 'modelo':modelo})

In [237]:
def linkedin(page):

    

    dato=[]
    #pages=np.arange(1,54,1)

    #for i in pages:

    page=(url3)

    html=req.get(page).content   # el html

    main=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]')
    for i in range(2,24):
        #coche=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]/div['+str(i)+']')
        

        for oferta in coche:

            # bucle para las ofertas
            modelo=oferta.find(class_='make-model-version').text.strip()   #modelo

            precio=oferta.find(class_='price').text.strip()   # precio

            #link=oferta.find('a').attrs['href']  # link de la oferta

            #lugar=oferta.find('span', class_="location").text.strip()  # lugar

            #combustible=oferta.find(class_="gas").text.strip()  # combustible

            #CV=oferta.find('span', class_='km').text.strip()      #km
            
            #year=oferta.find('span', class_='year').text.strip() #año



        dato.append({
            'modelo': modelo,
            'precio': precio,
            'link de la oferta': link,
            'location': lugar,
            'combustible': combustible,
            'CV': CV,
            'year':year
        })

    return pd.DataFrame(dato)

In [238]:
linkedin(url3)

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/3734714645.py:14: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  main=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]')
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/3734714645.py:22: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  modelo=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]/div['+str(i)+']/div[4]/a/strong').text.strip()   #modelo

NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="vo-results"]/div[7]/div[4]/div[4]/a/strong"}
  (Session info: chrome=100.0.4896.88)
Stacktrace:
Backtrace:
	Ordinal0 [0x00417413+2389011]
	Ordinal0 [0x003A9F61+1941345]
	Ordinal0 [0x0029C658+837208]
	Ordinal0 [0x002C91DD+1020381]
	Ordinal0 [0x002C949B+1021083]
	Ordinal0 [0x002F6032+1204274]
	Ordinal0 [0x002E4194+1130900]
	Ordinal0 [0x002F4302+1196802]
	Ordinal0 [0x002E3F66+1130342]
	Ordinal0 [0x002BE546+976198]
	Ordinal0 [0x002BF456+980054]
	GetHandleVerifier [0x005C9632+1727522]
	GetHandleVerifier [0x0067BA4D+2457661]
	GetHandleVerifier [0x004AEB81+569713]
	GetHandleVerifier [0x004ADD76+566118]
	Ordinal0 [0x003B0B2B+1968939]
	Ordinal0 [0x003B5988+1989000]
	Ordinal0 [0x003B5A75+1989237]
	Ordinal0 [0x003BECB1+2026673]
	BaseThreadInitThunk [0x77A0FA29+25]
	RtlGetAppContainerNamedObjectPath [0x77B57A7E+286]
	RtlGetAppContainerNamedObjectPath [0x77B57A4E+238]

In [334]:
pages = np.arange(1, 200, 1)
data=[]

for page in pages:
    
    page='https://www.coches.com/coches-segunda-mano/coches-ocasion.htm?page=' + str(page) 
    driver=webdriver.Chrome(PATH, options=opciones)
    driver.get(page)
    sleep(randint(1,2))
    cookies=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]')
    cookies.click()
    sleep(randint(2,10))
    soup = bs(driver.page_source, 'html.parser')
    my_table = soup.find_all(class_=['make-model-version', 'price','gas','cv','km','location','year'])

    for tag in my_table:
        data.append(tag.get_text().split('\n')

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/2215559095.py:7: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH, options=opciones)
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/2215559095.py:10: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cookies=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]')

In [356]:
precio=data[0::7]
Modelo=data[1::7]
combustible=data[2::7]
CV=data[3::7]
km=data[4:27860:7]
Lugar=data[5:27860:7]
año=data[6:27860:7]

coches.com=pd.DataFrame(precio)

coches.com['Modelo']=Modelo
coches.com['combustible']=combustible
coches.com['CV']=CV
coches.com['km']=km
coches.com['Lugar']=Lugar
coches.com['año']=año
coches.com

,0,Modelo,combustible,CV,km,Lugar,año
0,14.500 €,[Fiat Tipo],[ 1.0 City Live],[ Gasolina],"[, , Guadalajara, ...","[, , 2021, ...","[, 8 km, ]"
1,10.700 €,[Citroen C3 Comerc…],[ BlueHDi 75],[ Diesel],"[, , Valencia, ...","[, , 2016, ...","[, 211.000 km, ]"
2,4.999 €,[Volkswagen Jetta],[ 1.6 Trendline],[ Gasolina],"[, , Alicante, ...","[, , 2006, ...","[, 138.000 km, ]"
3,70.495 €,[Mercedes Clase E],[E 300 de],[ Híbrido],"[, , Madrid, ...","[, , 2022, ...","[, 0 km, ]"
4,21.990 €,[Kia Niro],[ 1.6 PHEV Drive],[ Híbrido],"[, , Valladolid, ...","[, , 2022, ...","[, 0 km, ]"
...,...,...,...,...,...,...,...
3975,19.200 €,"[, Hyundai Tucson 1.6 TGDI Li...",[ Gasolina],[ 176 cv],"[, 22.000 km, ]","[, , Cordoba, ]","[, , 2018, ]"
3976,24.900 €,"[, Seat León ST 2.0 TSI S&S, ...",[ Gasolina],[ 300 cv],"[, 64.530 km, ]","[, , Barcelona, ]","[, , 2017, ]"
3977,2.900 €,"[, Peugeot 307 SW 2.0HDI 110,...",[ Diesel],[ 110 cv],"[, 227.000 km, ]","[, , Madrid, ]","[, , 2003, ]"
3978,20.390 €,"[, Ds DS3 3 Crossback Puretech...",[ Gasolina],[ 155 cv],"[, 31.837 km, ]","[, , Madrid, ]","[, , 2019, ]"
3979,26.999 €,"[, Citroen C4 ë - Feel 100kW, ...",[ Eléctrico],[ 136 cv],"[, 3 km, ]","[, , Alava, ]","[, , 2020, ]"

In [256]:
data=[]


main=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]')
for i in range(2,24):
    coche=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]/div['+str(i)+']').text.split('\n')
    data.append(coche)


com=pd.DataFrame(data)

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/4122122044.py:2: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  main=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]')
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/4122122044.py:4: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  coche=driver.find_element_by_xpath('//*[@id="vo-results"]/div[7]/div['+str(i)+']').text.split('\n')

In [276]:
com['combustible']=0
com['CV']=0
com

,0,1,2,3,4,5,6,7,combustible,CV
0,Hace 3 días,46,17.500 €,Ford Ranger 2.2TDCI Cb. Sencilla Diesel 150 cv,101.000 km,Murcia,2015,None,0,0
1,Hace 15 horas,31,8.999 €,Citroen C5 1.6 THP Seduction Gasolina 156 cv,123.749 km,Madrid,2012,None,0,0
2,,None,None,None,None,None,None,None,0,0
3,Hace 4 días,16,17.300 €,Seat León 1.5 TGI GNC S&S FR Gasolina 130 cv,38.542 km,Pontevedra,2020,None,0,0
4,Hace 8 horas,30,KM0,13.990 €,Fiat 500 1.0 Hybrid Dolcevita Gasolina 70 cv,8.955 km,Madrid,2021,0,0
5,Hace 4 días,21,22.500 €,Bmw Serie 3 318d Diesel 150 cv,99.051 km,Pontevedra,2018,None,0,0
6,Hace 8 horas,21,21.500 €,Nissan Qashqai 1.7dCI N-Connecta Diesel 150 cv,59.000 km,Asturias,2019,None,0,0
7,,None,None,None,None,None,None,None,0,0
8,Hace 8 horas,20,9.900 €,Fiat Panda 1.3 Mjt Climbing 4x4 Diesel 75 cv,67.000 km,Asturias,2014,None,0,0
9,Hace 4 días,24,22.200 €,Kia Sportage 1.6 GDi Drive 4x2 Gasolina 132 cv,52.202 km,Pontevedra,2017,None,0,0
10,Hace 15 horas,28,17.290 €,Volkswagen Golf 2.0TDI CR BMT Sport Diesel 150 cv,75.834 km,Madrid,2015,None,0,0
11,Hace 8 horas,29,26.900 €,Nissan Qashqai 1.6dCi Tekna+ 4x2 Diesel 130 cv,71.320 km,Valencia,2018,None,0,0
12,Hace 5 días,66,16.900 €,Mercedes Clase C 250CDI BE Diesel 204 cv,180.000 km,Madrid,2012,None,0,0
13,Hace 5 días,54,29.500 €,Bmw Serie 4 420d Gran Coupé Diesel 190 cv,57.000 km,Madrid,2018,None,0,0
14,Hace 5 días,53,8.800 €,Cadillac SRX 3.6 V6 Sport Luxury Gasolina 258 cv,187.000 km,Madrid,2005,None,0,0
15,Hace 3 horas,12,12.790 €,Hyundai i30 1.6CRDi Essence 95 Diesel 95 cv,137.114 km,Madrid,2018,None,0,0
16,Hace 23 horas,21,19.899 €,Nissan Leaf 40 kWh Tekna Eléctrico 150 cv,35.279 km,Malaga,2019,None,0,0
17,Hace 9 horas,25,25.500 €,Citroen C5 BlueHDi S&S Diesel 130 cv,23.864 km,Madrid,2021,None,0,0
18,,None,None,None,None,None,None,None,0,0
19,Hace 9 horas,27,KM0,17.995 €,Peugeot 208 1.5 BlueHDi S&S Diesel 100 cv,0 km,Valencia,2022,0,0
20,Hace 9 horas,27,KM0,14.995 €,Peugeot 208 1.2 Puretech S&S Gasolina 75 cv,0 km,Valencia,2022,0,0
21,Hace 9 días,14,3.899 €,Mercedes Clase C 250Turbo Diesel Diesel 150 cv,258.000 km,Almeria,1996,None,0,0

In [451]:
def cochescom(pages):     
        pages = np.arange(1, 5, 1)
        data=[]

        for page in pages:

            page='https://www.coches.com/coches-segunda-mano/coches-ocasion.htm?page=' + str(page) 
            driver=webdriver.Chrome(PATH, options=opciones)
            driver.get(page)
            sleep(randint(1,2))
            cookies=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]')
            cookies.click()
            sleep(randint(2,10))
            soup = bs(driver.page_source, 'html.parser')

            modelo =[e.text.split('\n') for e in soup.find_all(class_='make-model-version')]
            precio=[i.text.split('\n') for i in soup.find_all(class_='price')]
            combustible=[c.text.split('\n') for c in soup.find_all(class_='gas')]
            CV=[cv.text.split('\n') for cv in soup.find_all(class_='cv')]
            km=[km.text.split('\n') for km in soup.find_all(class_='km')]
            lugar=[l.text.split('\n') for l in soup.find_all(class_='location')]
            año=[a.text.split('\n') for a in soup.find_all(class_='year')]
            link=[li.find('a').attrs['href'] for li in soup.find_all(class_='pill-information')]

            flat_list_modelo = [item for modelo in model for item in modelo]
            flat_list_precio = [item for precio in price for item in precio]
            flat_list_gas = [item for combustible in gas for item in combustible]
            flat_list_cv = [item for CV in horse for item in CV]
            flat_list_km = [item for km in dis for item in km]
            flat_list_lugar = [item for lugar in place for item in lugar]
            flat_list_año = [item for año in year for item in año]
            flat_list_link = [item for link in li for item in link]


            coches=pd.DataFrame(flat_list_modelo)
            
            coches['precio']=flat_list_precio
            coches['combustible']=flat_list_gas
            coches['CV']=flat_list_cv
            coches['km']=flat_list_km
            coches['lugar']=flat_list_lugar
            coches['año']=flat_list_año
            coches['link']=flat_list_link
            coches
            
        
        
        return coches

In [471]:
pages = np.arange(1, 2, 1)
data=[]
model=[]
price=[]
gas=[]
horse=[]
dis=[]
place=[]
year=[]
li=[]

for page in pages:

    page='https://www.coches.com/coches-segunda-mano/coches-ocasion.htm?page=' + str(page) 
    driver=webdriver.Chrome(PATH, options=opciones)
    driver.get(page)
    sleep(randint(1,2))
    cookies=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]')
    cookies.click()
    sleep(randint(2,10))
    soup = bs(driver.page_source, 'html.parser')

    modelo =[e.text.strip().split('\n') for e in soup.find_all(class_='make-model-version')]
    precio=[i.text.strip().split('\n') for i in soup.find_all(class_='price')]
    combustible=[c.text.strip().split('\n') for c in soup.find_all(class_='gas')]
    CV=[cv.text.strip().split('\n') for cv in soup.find_all(class_='cv')]
    km=[km.text.strip().split('\n') for km in soup.find_all(class_='km')]
    lugar=[l.text.strip().split('\n') for l in soup.find_all(class_='location')]
    año=[a.text.strip().split('\n') for a in soup.find_all(class_='year')]
    link=[li.find('a').attrs['href'] for li in soup.find_all(class_='pill-information')]

    model.append(modelo)
    price.append(precio)
    gas.append(combustible)
    horse.append(CV)
    dis.append(km)
    place.append(lugar)
    year.append(año)
    li.append(link)
    
    flat_list_modelo = [item for modelo in model for item in modelo]
    flat_list_precio = [item for precio in price for item in precio]
    flat_list_gas = [item for combustible in gas for item in combustible]
    flat_list_cv = [item for CV in horse for item in CV]
    flat_list_km = [item for km in dis for item in km]
    flat_list_lugar = [item for lugar in place for item in lugar]
    flat_list_año = [item for año in year for item in año]
    flat_list_link = [item for link in li for item in link]
    
    
    coches=pd.DataFrame(flat_list_modelo)
    #coches['0']=coches['modelo']
    coches['precio']=flat_list_precio
    coches['combustible']=flat_list_gas
    coches['CV']=flat_list_cv
    coches['km']=flat_list_km
    coches['lugar']=flat_list_lugar
    coches['año']=flat_list_año
    coches['link']=flat_list_link
    coches

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/162847488.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH, options=opciones)
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/162847488.py:18: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cookies=driver.find_element_by_xpath('//*[@id="onetrust-accept-btn-handler"]')

In [475]:

coches

,0,precio,combustible,CV,km,lugar,año,link
0,Volkswagen 1.6TDI Advance,[19.990 €],[Diesel],[115 cv],[92.000 km],[Tarragona],[2019],https://www.coches.com/coches-segunda-mano/oca...
1,Citroen Jumpy e- Combi Talla M,[38.900 €],[Eléctrico],[136 cv],[40 km],[Alicante],[2021],https://www.coches.com/km0/seminuevo-citroen-j...
2,Mercedes Clase C Estate 220d,[22.990 €],[Diesel],[170 cv],[44.200 km],[Madrid],[2016],https://www.coches.com/coches-segunda-mano/oca...
3,Audi TT Coupé 1.8T quattro,[8.500 €],[Gasolina],[225 cv],[185.000 km],[Malaga],[2002],https://www.coches.com/coches-segunda-mano/oca...
4,Citroen Berlingo E- Multispace Feel,[17.000 €],[Eléctrico],[67 cv],[13.840 km],[Alicante],[2018],https://www.coches.com/coches-segunda-mano/oca...
5,Audi Q3 35 TDI Advanced S,[31.490 €],[Diesel],[150 cv],[75.000 km],[Zaragoza],[2019],https://www.coches.com/coches-segunda-mano/oca...
6,Ford C-Max 2.0TDCi Auto-S&S,[10.200 €],[Diesel],[150 cv],[145.000 km],[Badajoz],[2017],https://www.coches.com/coches-segunda-mano/oca...
7,Seat León 2.0TDI CR S&S,[25.900 €],[Diesel],[150 cv],[20.000 km],[Barcelona],[2020],https://www.coches.com/coches-segunda-mano/oca...
8,Citroen C4 1.2 PureTech Feel,[18.900 €],[Gasolina],[130 cv],[9.000 km],[Pontevedra],[2021],https://www.coches.com/km0/seminuevo-citroen-c...
9,Renault Mégane 1.5dCi Life 95,[8.100 €],[Diesel],[95 cv],[109.100 km],[Madrid],[2014],https://www.coches.com/coches-segunda-mano/oca...
10,Bmw Serie 3 318d Modern,[12.210 €],[Diesel],[143 cv],[121.709 km],[Madrid],[2012],https://www.coches.com/coches-segunda-mano/oca...
11,Mg ZS Luxury 72kWh 115kW,[35.950 €],[Eléctrico],[156 cv],[0 km],[Valladolid],[2022],https://www.coches.com/km0/seminuevo-mg-zs-lux...
12,Mg HS e 1.5 T-GDI Luxury,[31.500 €],[Híbrido],[162 cv],[6 km],[Madrid],[2022],https://www.coches.com/km0/seminuevo-mg-hs-e-1...
13,Seat Ateca 1.5 EcoTSI S&S Style,[24.200 €],[Gasolina],[150 cv],[21.000 km],[Cordoba],[2021],https://www.coches.com/coches-segunda-mano/oca...
14,Kia Sportage 1.6 T-GDi Drive,[23.900 €],[Gasolina],[150 cv],[0 km],[Valladolid],[2022],https://www.coches.com/km0/seminuevo-kia-sport...
15,Land Rover 2.0 I4 MHEV,[46.170 €],[Gasolina],[200 cv],[14.309 km],[Valencia],[2019],https://www.coches.com/coches-segunda-mano/oca...
16,Audi A3 Sportback 35TDI S,[26.910 €],[Diesel],[150 cv],[20.228 km],[Valencia],[2020],https://www.coches.com/coches-segunda-mano/oca...
17,Mazda MX-5 ST 1.5 Skyactiv-G,[18.495 €],[Gasolina],[132 cv],[24.900 km],"[Palmas, Las]",[2020],https://www.coches.com/coches-segunda-mano/oca...
18,Fiat Tipo 1.0 Live,[15.290 €],[Gasolina],[100 cv],[7.000 km],[Castellon],[2021],https://www.coches.com/km0/seminuevo-fiat-tipo...
19,Mercedes Vito e Furgón Larga,[36.790 €],[Eléctrico],[116 cv],[13.200 km],[Sevilla],[2019],https://www.coches.com/coches-segunda-mano/oca...

## KAGGLE

In [477]:
import csv

In [483]:
#ith open(r'/data/coches-de-segunda-mano-sample.csv', newline='') as csvfile:
kagle = pd.read_csv (r'data\coches-de-segunda-mano-sample.csv')
kagle= pd.DataFrame(kagle, columns= ['url','company','make','model','version','price','price_financed','fuel','year','doors','shift','color','photos','is_professional','dealer','province','country','publish_date','insert_date'])

In [484]:
kagle

,url,company,make,model,version,price,price_financed,fuel,year,doors,shift,color,photos,is_professional,dealer,province,country,publish_date,insert_date
0,e158ae0ca53119ca199c28c36b5c2fcd,9881bcdd5a0ad4733037b3fb25e69c3a,SEAT,Toledo,SEAT Toledo 4p.,950,NaN,Diésel,2000.0,4,Manual,Verde,5,False,0f4bb8455d27349b8273109b66a847f3,Navarra,Spain,2020-12-18 10:47:13,2021-01-15 00:00:00
1,ff267ebb7e700246f47f84f3db660b4b,9881bcdd5a0ad4733037b3fb25e69c3a,CITROEN,C1,CITROEN C1 PureTech 60KW 82CV Feel 5p.,6200,NaN,Gasolina,2017.0,5,Manual,Blanco,6,True,Autos Raymara,Tenerife,Spain,2021-01-02 11:25:40,2021-01-15 00:00:00
2,de4b02db28ea7786c622b969be10c7c7,9881bcdd5a0ad4733037b3fb25e69c3a,FORD,Transit Connect,FORD Transit Connect Van 1.5 TDCi 100cv Ambien...,7851,7024.0,Diésel,2016.0,4,Manual,Blanco,10,True,Auto 96,Barcelona,Spain,2020-12-16 10:51:45,2021-01-15 00:00:00
3,0449972a4d07594acf92e9a7dd28b39c,9881bcdd5a0ad4733037b3fb25e69c3a,VOLKSWAGEN,Caravelle,VOLKSWAGEN Caravelle Largo 2.0 TDI 140 Comfort...,19426,NaN,Diésel,2014.0,4,Manual,Blanco,9,True,Inniauto,Navarra,Spain,2020-11-25 11:09:14,2021-01-15 00:00:00
4,12c4fa49bd4fdf23f19ecf396d3f02ef,9881bcdd5a0ad4733037b3fb25e69c3a,FORD,Transit,FORD Transit 350 96kW L4 Ambiente Propulsion T...,22850,22800.0,Diésel,2017.0,2,Manual,Blanco,4,True,"Autofleet España,s.l",Sevilla,Spain,2021-01-12 20:00:34,2021-01-15 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,730210734bfbe1d3df878d5df71246f2,9881bcdd5a0ad4733037b3fb25e69c3a,HYUNDAI,i30,HYUNDAI i30 1.4 TGDI Tecno Fastback DCT 5p.,18490,16490.0,Gasolina,2018.0,5,Automático,Gris / Plata,26,True,Flexicar Málaga,Málaga,Spain,2020-11-24 19:59:52,2021-01-15 00:00:00
49996,732b04fb47dd9559dbdcd099c5af484e,9881bcdd5a0ad4733037b3fb25e69c3a,RENAULT,Laguna,RENAULT Laguna Coupe Limited 2.0 Energy dCi 15...,14500,13551.0,Diésel,2015.0,2,Manual,KNG Gris Casiopea (metalizado),30,True,Ocasion Plus,Málaga,Spain,2021-01-13 17:02:41,2021-01-15 00:00:00
49997,c10afb53957fb8012707239bdfa66018,9881bcdd5a0ad4733037b3fb25e69c3a,PEUGEOT,108,PEUGEOT 108 TOP Allure VTi 52kW 72CV 5p.,11000,9000.0,Gasolina,2019.0,5,Manual,Gris / Plata,17,True,Psa Retail Huelva,Huelva,Spain,2021-01-08 16:47:24,2021-01-15 00:00:00
49998,f74363a6688ba11b71b4d980a959b8d3,9881bcdd5a0ad4733037b3fb25e69c3a,AUDI,RS4,AUDI RS4 Avant 4.2 FSI 450cv quattro 5p.,47900,NaN,Gasolina,2013.0,5,Automático,Gris / Plata (Antracita),20,True,Codigocar Lugo,Lugo,Spain,2021-01-13 16:22:53,2021-01-15 00:00:00
49999,3d60801ccb96ef038747130e8a34ceda,9881bcdd5a0ad4733037b3fb25e69c3a,CITROEN,C2,CITROEN C2 1.4 HDI VTR Plus 3p.,2790,NaN,Diésel,2006.0,3,Manual,Negro,21,True,AUTOVALENCIA 19,Barcelona,Spain,2021-01-10 16:32:41,2021-01-15 00:00:00

## MILANUNCIOS

In [504]:
url2='https://es.wallapop.com/app/search?category_ids=100&filters_source=seo_landing&longitude=-3.69196&latitude=40.41956'

In [494]:
pages = np.arange(1, 2, 1)
data=[]
model=[]
price=[]
gas=[]
horse=[]
dis=[]
place=[]
year=[]
li=[]



page=url2  
driver=webdriver.Chrome(PATH, options=opciones)
driver.get(page)
sleep(randint(1,2))
cookies=driver.find_element_by_xpath('//*[@id="didomi-notice-agree-button"]')
cookies.click()
sleep(randint(2,10))
roll=driver.find_element_by_xpath('/html/body/div[2]/div[1]/div[4]/div[1]/div/div/form/input')
roll.click()
driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')

soup = bs(driver.page_source, 'html.parser')

modelo =[e.text.strip().split('\n') for e in soup.find_all(class_='product-info-title')]
precio=[i.text.strip().split('\n') for i in soup.find_all(class_='product-info-price')]
combustible=[c.text.strip().split('\n') for c in soup.find_all(class_='card-info')]
CV=[cv.text.strip().split('\n') for cv in soup.find_all(class_='cv')]
km=[km.text.strip().split('\n') for km in soup.find_all(class_='km')]
lugar=[l.text.strip().split('\n') for l in soup.find_all(class_='location')]
año=[a.text.strip().split('\n') for a in soup.find_all(class_='year')]
link=[li.find('a').attrs['href'] for li in soup.find_all(class_='pill-information')]

model.append(modelo)
price.append(precio)
gas.append(combustible)
horse.append(CV)
dis.append(km)
place.append(lugar)
year.append(año)
li.append(link)

flat_list_modelo = [item for modelo in model for item in modelo]
flat_list_precio = [item for precio in price for item in precio]
flat_list_gas = [item for combustible in gas for item in combustible]
flat_list_cv = [item for CV in horse for item in CV]
flat_list_km = [item for km in dis for item in km]
flat_list_lugar = [item for lugar in place for item in lugar]
flat_list_año = [item for año in year for item in año]
flat_list_link = [item for link in li for item in link]


coches=pd.DataFrame(flat_list_modelo)
#coches['0']=coches['modelo']
coches['precio']=flat_list_precio
coches['combustible']=flat_list_gas
coches['CV']=flat_list_cv
coches['km']=flat_list_km
coches['lugar']=flat_list_lugar
coches['año']=flat_list_año
coches['link']=flat_list_link
coches

C:\Users\alima\AppData\Local\Temp/ipykernel_23336/1855332.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver=webdriver.Chrome(PATH, options=opciones)
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/1855332.py:18: DeprecationWarning: find_element_by_xpath is deprecated. Please use find_element(by=By.XPATH, value=xpath) instead
  cookies=driver.find_element_by_xpath('//*[@id="app"]/div[2]/div[1]/div/div/div/footer/div/button[2]')
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/1855332.py:22: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  km=[km.text.strip().split('\n') for km in driver.find_elements_by_xpath('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article['+str(i)+']/div/div/a[2]/div[2]/ul/li[1]/span/span')]
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/1855332.py:34: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  km=[km.text.strip().split('\n') for km in driver.find_elements_by_xpath('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article['+str(i)+']/div/div/a[2]/div[2]/ul/li[1]/span/span')]
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/1855332.py:36: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  año=[a.text.strip().split('\n') for a in driver.find_elements_by_xpath('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article['+str(i)+']/div/div/a[2]/div[2]/ul/li[2]/span/span')]
C:\Users\alima\AppData\Local\Temp/ipykernel_23336/1855332.py:37: DeprecationWarning: find_elements_by_xpath is deprecated. Please use find_elements(by=By.XPATH, value=xpath) instead
  precio=[i.text.strip().split('\n') for i in driver.find_elements_by_xpath('//*[@id="app"]/div[2]/div[3]/div[1]/div[2]/div[3]/div[1]/main/div[2]/article['+str(i)+']/div/div/a[1]/div[1]/div/p/span[2]')]

In [534]:
def wallapop(url2):
    
    page=url2  
    driver=webdriver.Chrome(PATH, options=opciones)
    driver.get(page)
    sleep(randint(1,2))
    cookies=driver.find_element_by_xpath('//*[@id="didomi-notice-agree-button"]')
    cookies.click()
    sleep(randint(2,10))
    roll=driver.find_element_by_xpath('//*[@id="btn-load-more"]/button')
    roll.click()
    lastHeight = driver.execute_script("return document.documentElement.scrollHeight")
    print('lastHeight', lastHeight)
    while True:

        driver.execute_script('window.scrollTo(0, document.body.scrollHeight);')
        height = driver.execute_script("return document.documentElement.scrollHeight")
        newHeight = driver.execute_script("window.scrollTo(0, " + str(height) + ");")
        time.sleep(0.2)
        if newHeight == lastHeight:
            break
        lastHeight = newHeight


    soup = bs(driver.page_source, 'html.parser')

    modelo =[e.text.strip().split('\n') for e in soup.find_all(class_='ItemCardWide__title d-inline-block text-truncate w-100')]
    precio=[i.text.strip().split('\n') for i in soup.find_all(class_='ItemCardWide__price ItemCardWide__price--bold')]
    combustible=[c.text.strip().split('\n') for c in soup.find_all(class_='ItemCardWide__extraInfo d-block mt-1')]
    
    df=pd.DataFrame(modelo)
    df['precio']=precio
    df['caracteristicas']=combustible
    
    return df

In [529]:
len(modelo)

120

In [531]:
df=pd.DataFrame(modelo)
df['precio']=precio
df['caracteristicas']=combustible

In [532]:
df

,0,precio,caracteristicas
0,SEAT Ibiza 1.2 TSI Reference 66 kW (90 CV),[9.900€],[GasolinaManual90 cv201760000 km]
1,BMW Serie 5 520d 135 kW (184 CV),[14.890€],[DiéselAutomático184 cv2012208000 km]
2,Volkswagen Caddy Kombi 2.0 TDI SCR BMT 4MOTION...,[14.180€],[DiéselManual122 cv2016158308 km]
3,Audi A6 2014,[14.500€],[DiéselAutomático177 cv2014158000 km]
4,Peugeot 306 SEDAN BOULEVARD HDI 90cv,[990€],[DiéselManual90 cv2000263370 km]
...,...,...,...
115,CUPRA Ateca 2.0 TSI 4Drive DSG 221 kW (300 CV),[35.354€],[GasolinaAutomático300 cv202123165 km]
116,Audi A3 Sportback design 35 TDI 110 kW (150 CV...,[28.990€],[DiéselAutomático150 cv202019500 km]
117,Peugeot 308 SW 1.6 BlueHDi MBC Active 88 kW (1...,[11.890€],[DiéselManual120 cv2017155809 km]
118,Mazda 6 SW 2.2 Skyactiv-D 150cv Style 5p Naveg...,[15.350€],[DiéselAutomático150 cv2017131150 km]
119,Volkswagen Crafter 2015,[15.000€],[DiéselManual136 cv2015161000 km]